leader_pid_controller:
  ros__parameters:
    state_topic: /wamv/state/vehicle
    path_topic: /planner/reference_path
    left_thrust_topic: /wamv/thrusters/left/thrust
    right_thrust_topic: /wamv/thrusters/right/thrust
    left_position_topic: /wamv/thrusters/left/pos
    right_position_topic: /wamv/thrusters/right/pos
    success_topic: /experiment/success
    control_rate: 10.0
    target_speed: 1.0
    lookahead_distance: 3.0
    goal_tolerance: 1.0
    heading_slowdown_angle: 0.5283476090300474
    speed_kp: 77.49640833032895
    speed_ki: 40.0
    speed_kd: 49.19260599818982
    speed_integral_limit: 10.0
    heading_kp: 1388.5269897997275
    heading_ki: 26.45969942764789
    heading_kd: 201.59814882921654
    heading_integral_limit: 1.5
    brake_kp: 177.8935198208073
    brake_ki: 60.634764417119634
    brake_kd: 10.647182804717701
    brake_integral_limit: 1.0
    max_brake_thrust: 500.0
    stop_speed_tolerance: 0.05
    recovery_target_speed: 0.25
    recovery_brake_distance: 0.75
    recovery_align_tolerance: 0.15
    recovery_realign_tolerance: 0.35
    recovery_max_forward_thrust: 250.0
    recovery_max_turn_thrust: 250.0
    hold_duration: 5.0
    max_forward_thrust: 700.0
    max_turn_thrust: 400.0
    max_total_thrust: 1000.0
